# Generated by Django 3.0.6 on 2020-05-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0005_auto_20200511_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='salt',
            field=models.CharField(default='HugGQDkOrs+MOMRt0mvznQ==', max_length=25),
        ),
    ]
