# Generated by Django 3.0.6 on 2020-05-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0009_auto_20200512_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='194g8EiJg9FWAZSF0ykNaA==', max_length=25),
        ),
    ]
