# Generated by Django 3.0.6 on 2020-05-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0012_auto_20200514_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='i2LEHrHYLWDMKCWeKYQmLQ==', max_length=25),
        ),
    ]
