# Generated by Django 3.0.5 on 2020-05-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='codigo_token',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='admin',
            name='id_chat',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='admin',
            name='id_token',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='salt',
            field=models.CharField(default='qcAld7OpCQqq/LQjUPS+mA==', max_length=25),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='usuario',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
