# Generated by Django 3.0.5 on 2020-05-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0003_auto_20200506_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('ultima_peticion', models.DateTimeField()),
                ('intentos', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='salt',
            field=models.CharField(default='SaFHxg0eCL/JG7GwmkdpaA==', max_length=25),
        ),
    ]
