# Generated by Django 3.0.6 on 2020-05-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0007_auto_20200511_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default=None, max_length=15)),
                ('password', models.CharField(default=None, max_length=100)),
                ('salt', models.CharField(default='SAtZ6bOTQXSRzk8DdCbcYQ==', max_length=25)),
                ('id_token', models.CharField(default=None, max_length=50)),
                ('id_chat', models.CharField(default=None, max_length=10)),
                ('codigo_token', models.CharField(blank=True, default=None, max_length=25, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='salt',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
