# Generated by Django 3.0.5 on 2020-05-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0010_auto_20200513_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='KSdKTUEXiuoHb/kTYF5vdQ==', max_length=25),
        ),
    ]
