# Generated by Django 3.0.5 on 2020-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0011_auto_20200514_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default=None, max_length=110),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='qlEyr9mkEohQwUvMpSf1EA==', max_length=25),
        ),
    ]
