# Generated by Django 3.0.5 on 2020-05-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0002_auto_20200506_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='salt',
            field=models.CharField(default='wpLqlvyqw3wrX9ADukuspw==', max_length=25),
        ),
    ]
