# Generated by Django 3.0.6 on 2020-07-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0014_auto_20200603_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=None, max_length=15)),
                ('api_user', models.CharField(default=None, max_length=15)),
                ('api_password', models.CharField(default=None, max_length=100)),
                ('api_iv', models.CharField(default=None, max_length=16)),
                ('admin', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
        ),
    ]
