# Generated by Django 3.0.6 on 2020-07-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorPS', '0015_servers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='api_iv',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
