version: '3.1'

services:

  webservices:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      URL_SERVICIOS: ${URL_SERVICIOS}
      CLIENTE_SERVICIOS_USR: ${CLIENTE_SERVICIOS_USR}
      CLIENTE_SERVICIOS_PWD: ${CLIENTE_SERVICIOS_PWD}
    build: .
    restart: always
    container_name: monitor_backend
    volumes:
      - ./webServices:/code
    depends_on:
      - backend_scan
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "250M"   
    pid: host      
    
  backend_scan:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data:/var/lib/mysql
  
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - webservices
    ports:
      - 8000:80

  #pid: "host"

  #terminal:
  #  image: terminal
  #  environment:
  #    USER: ${USER}
  #    PASS: ${PASS}
  #  restart: always
  #  ports:
  #    - 6767:7681
  #  networks:
  #    - net_terminal

#networks:
#  net_terminal:
#    external: true